// File generated by Antigravity for MycoApp Firebase configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5StGNbE15cDr7CmSOdcQZ0RHkOFFDhEI',
    appId: '1:886418118468:web:2ed58397e1d3ce58f42911',
    messagingSenderId: '886418118468',
    projectId: 'mycoapp-ferme-69081',
    authDomain: 'mycoapp-ferme-69081.firebaseapp.com',
    storageBucket: 'mycoapp-ferme-69081.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5StGNbE15cDr7CmSOdcQZ0RHkOFFDhEI',
    appId: '1:886418118468:android:2ed58397e1d3ce58f42911',
    messagingSenderId: '886418118468',
    projectId: 'mycoapp-ferme-69081',
    storageBucket: 'mycoapp-ferme-69081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5StGNbE15cDr7CmSOdcQZ0RHkOFFDhEI',
    appId: '1:886418118468:ios:2ed58397e1d3ce58f42911',
    messagingSenderId: '886418118468',
    projectId: 'mycoapp-ferme-69081',
    storageBucket: 'mycoapp-ferme-69081.firebasestorage.app',
    androidClientId: '886418118468-android.apps.googleusercontent.com',
    iosBundleId: 'com.mycoapp.farm',
  );
}
